import { StickerStyle } from '@/lib/story-editor/types';
import { NDKStoryStickerType } from '@/lib/story-editor/types';
import { registerStickerStyles } from '@/lib/story-editor/styles/stickerStyles';

// Define 10 different styles for text stickers
const textStickerStyles: StickerStyle[] = [
    {
        id: 'default',
        name: 'Default',
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: 16,
        color: 'white',
        fontSize: 16,
        fontWeight: 'bold',
    },
    {
        id: 'neon',
        name: 'Neon',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        borderRadius: 16,
        color: '#0ff',
        fontSize: 18,
        fontWeight: 'bold',
        textShadowColor: '#0ff',
        textShadowOffset: { width: 0, height: 0 },
        textShadowRadius: 10,
    },
    {
        id: 'minimal',
        name: 'Minimal',
        backgroundColor: 'rgba(255, 255, 255, 0.8)',
        borderRadius: 8,
        color: '#000',
        fontSize: 16,
        fontWeight: 'normal',
    },
    {
        id: 'retro',
        name: 'Retro',
        backgroundColor: 'rgba(255, 220, 0, 0.8)',
        borderRadius: 0,
        borderWidth: 2,
        borderColor: '#000',
        color: '#000',
        fontSize: 16,
        fontWeight: 'bold',
        fontStyle: 'italic',
    },
    {
        id: 'glitch',
        name: 'Glitch',
        backgroundColor: 'rgba(255, 0, 128, 0.7)',
        borderRadius: 4,
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
        textShadowColor: '#0ff',
        textShadowOffset: { width: 2, height: 2 },
        textShadowRadius: 0,
    },
    {
        id: 'bubble',
        name: 'Bubble',
        backgroundColor: 'rgba(100, 200, 255, 0.8)',
        borderRadius: 24,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    {
        id: 'outline',
        name: 'Outline',
        backgroundColor: 'transparent',
        borderWidth: 2,
        borderColor: '#fff',
        borderRadius: 16,
        color: '#fff',
        fontSize: 16,
        fontWeight: 'normal',
    },
    {
        id: 'paper',
        name: 'Paper',
        backgroundColor: 'rgba(255, 252, 235, 0.9)',
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#d0c8b0',
        color: '#6d4c41',
        fontSize: 16,
        fontWeight: 'normal',
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
    },
    {
        id: 'gradient',
        name: 'Gradient',
        backgroundColor: 'rgba(120, 0, 255, 0.7)',
        borderRadius: 16,
        color: '#fff',
        fontSize: 18,
        fontWeight: 'bold',
    },
    {
        id: 'typed',
        name: 'Typewriter',
        backgroundColor: 'rgba(0, 0, 0, 0.8)',
        borderRadius: 4,
        color: '#7FFF00',
        fontSize: 14,
        fontWeight: '400',
    },
];

// Register the styles
registerStickerStyles(NDKStoryStickerType.Text, textStickerStyles);

export default textStickerStyles; 