name: Olas Mobile App Tests
description: End-to-end tests for Olas mobile app

appId:
    android: com.pablof7z.snapstr
    ios: com.pablof7z.snapstr

config:
    screenshotsPath: './.maestro/screenshots'
    reportPath: './.maestro/report'
    deviceCapabilities:
        - 'SCREENSHOTS'
        - 'VIDEO'
    deviceId: '46FC18EA-59F0-4B47-BE94-811B787E6666'
