name: Olas Mobile App Tests
description: End-to-end tests for Olas mobile app

appId:
    android: com.pablof7z.snapstr
    ios: com.pablof7z.snapstr

config:
    screenshotsPath: './.maestro/screenshots'
    reportPath: './.maestro/report'
    deviceCapabilities:
        - 'SCREENSHOTS'
        - 'VIDEO'
    deviceId: '29BF3D2B-4202-4DC4-8EDB-B4D5BD27E7B9'
